### PR TITLE
PHP 8.0 support 🚀

### PR DESCRIPTION
**Pull request by tortuetorche**
An also Laravel 6 (LTS) and 8 support

**TODOS**:
* [x] Some real app testing

### CODE REVIEW

**Comment by tortuetorche** [comment]
Build (from my fork) passed: https://travis-ci.com/github/tortuetorche/breadcrumbs/builds/206263637

**Comment by tortuetorche** [comment]
FYI, it works as expected with PHP 8.0 and a real Laravel 6 application and also a real Laravel 8 application!

**Comment by tortuetorche** [comment]
Build (from my fork) passed: https://travis-ci.com/github/tortuetorche/breadcrumbs/builds/206511425

**Comment by dwightwatson** [comment]
Thanks for this, I've tagged `1.2.0`. I'll leave the remaining PR for when I have more time to work on the new version.

**Pull request merged**
