### PR TITLE
PHP 8 support 🚀 for version 2.0

### PR DESCRIPTION
**Pull request by tortuetorche**

### CODE REVIEW

**Comment by tortuetorche** [comment]
Build (from my fork) passed: https://travis-ci.com/github/tortuetorche/breadcrumbs/builds/205634244

By the way, you should [migrate](https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/) from the legacy https://travis-ci.org to the new https://travis-ci.com, to get faster builds 👍
I did it for my repositories, it's like night and day 😆

**Comment by dwightwatson** [comment]
Thanks for this, I'll get a new tagged release out shortly. I'll check out the changes to Travis as I wasn't aware of those.

**Comment by dwightwatson** [comment]
Tagged `1.1.1`

**Comment by dwightwatson** [comment]
I just realised this went in to develop which is where I’ve been working on a new version that’s a total departure from what’s in master. The latest tag is actually on that branch and not this one. 

I’m not sure I’m going to be in a position to finish this new version soon as it requires a bit more work. I’ll look at adding PHP 8 support to the master branch next time I’m at a computer.

**Comment by tortuetorche** [comment]
> I’m not sure I’m going to be in a position to finish this new version soon as it requires a bit more work.

Oh, I see

> I’ll look at adding PHP 8 support to the master branch next time I’m at a computer.

I can try if you want

**Comment by tortuetorche** [comment]
> I’ll look at adding PHP 8 support to the master branch next time I’m at a computer.

WIP: https://github.com/dwightwatson/breadcrumbs/pull/18

**Pull request merged**
